
package UI.componentes;

import java.awt.Graphics;

/**
 * Clase que representa un tablero para el juego.
 * @author Daniel Parra, Jesus Ramses, Jose Felix
 */
public class TableroPanel extends javax.swing.JPanel {

    public TableroPanel() {
        initComponents();
        
    }

    /**
     * Metodo que pinta el tablero del juego en la pantalla.
     * @param g 
     */
    @Override
    public void paint(Graphics g) {
        super.paint(g); 
        
        //g.drawLine(0, 0, 100, 100);
        
        // Ejemplo tablero 20x20
        
        int alto = this.getSize().height;
        int ancho = this.getSize().width;
        
        int separacion = Math.floorDiv(alto, 20);
        
        for (int x = 0; x < ancho; x+=separacion) {
            for (int y = 0; y < alto; y+=separacion) {
                g.drawOval(x, y, 5, 5);
                g.fillOval(x, y, 5, 5);
            }
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
